name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Enable Gradle caching
        uses: gradle/actions/setup-gradle@v3

      # Generate wrapper ONLY if gradlew or wrapper JAR is missing
      - name: Ensure Gradle wrapper exists
        run: |
          set -euxo pipefail
          if [ ! -f gradlew ] || [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Gradle wrapper missing -> installing system Gradle to generate it"
            sudo apt-get update
            sudo apt-get install -y gradle
            gradle --version
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x gradlew

      - name: Verify Gradle projects
        run: |
          ./gradlew --version
          ./gradlew projects

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
