name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17 (required by Gradle 9)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Set up Gradle caching
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      # Fix gradlew permission issue
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      # Upload Debug APK as artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
