name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup JDK (Android requires JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Step 3: Generate Gradle Wrapper if missing
      - name: Ensure Gradle Wrapper
        run: |
          if [ ! -f ./gradlew ]; then
            echo "Gradle wrapper not found, generating..."
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x ./gradlew

      # Step 4: Build Debug APK
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      # Step 5: Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
